from BCM import BCM
from BCM import BCM_LawCooper
from BCM import BCM_Dynamic_Weight_Limits
from BCM_TwoThreshold import BCM_TwoThreshold
from BCM_TwoThreshold_Harel import BCM_TwoThreshold_Harel
from BCM_TwoThreshold_OLD import BCM_TwoThreshold_OLD
from constant_connection import Constant_Connection
from Hebb import Hebb
from Miller2014 import Miller2014_Eq3
from Miller2014 import Miller2014_Eq5
import process